package GUI;

import BLL.ChiTietHD_BLL;
import BLL.HangHoaBLL;
import BLL.KhachHangBLL;
import BLL.NhanVienBLL;
import BLL.HDonBLL;
import DTO.ChiTietHD_DTO;
import DTO.HangHoaDTO;
import DTO.KhachHangDTO;
import DTO.NhanVienDTO;
import DTO.HDonDTO;
import java.awt.*;
import java.sql.Date;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class Frm_LapHD extends javax.swing.JFrame {

    
    String[] header = { "STT","MÃ HÀNG","TÊN HÀNG","ĐƠN GIÁ","SỐ LƯỢNG","THÀNH TIỀN"};
    DefaultTableModel dtm = new DefaultTableModel(header, 0); 
    int stt=0;
    int tongTien=0;
    public Frm_LapHD() {
        initComponents();
        addControl();    
        setMaHD();
        addComboBoxMaHD();
        //tfDate.setText(String.valueOf(java.time.LocalDate.now()));
        dateHD.setDate(Date.valueOf(java.time.LocalDate.now()));
    }
    
    private void addControl(){
        
        panel.setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        this.setTitle("PHẦN MỀM QUẢN LÝ CỬA HÀNG BÁNH KẸO MAILISA");
        btnadd.setBackground(Color.PINK);        
        btnsearch.setBackground(Color.PINK);  
        btn.setBackground(Color.PINK); 
        btnReport.setBackground(Color.PINK);
        tf1.setText("Nhập Mã hàng");
        tf2.setText("Nhập số lượng");
        tf1.setForeground(Color.DARK_GRAY);
        tf2.setForeground(Color.DARK_GRAY);
    }
    
    private void setMaHD(){
        HDonBLL hdBLL=new HDonBLL();
        lblMAHD.setText(hdBLL.getMaHD());
    }
    
    private void addComboBoxMaHD(){
        ArrayList<HDonDTO> arr = new ArrayList<HDonDTO>();
	 HDonBLL hdBLL = new HDonBLL();
	 arr = hdBLL.getAllHDon();	 
	 HDonDTO hdDTO = new HDonDTO();
	 for (int i = 0; i < arr.size(); i++) {
		 hdDTO = arr.get(i);
		 cbMaHD.addItem(hdDTO.getMA_HD());		 
	 }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lblmaphieu = new javax.swing.JLabel();
        lblmanhacc = new javax.swing.JLabel();
        lblngaylap = new javax.swing.JLabel();
        lblmanv = new javax.swing.JLabel();
        lbltongtien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbxuat = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMAHD = new javax.swing.JLabel();
        cbMaHD = new javax.swing.JComboBox<>();
        lblManv = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        lTien = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn = new javax.swing.JButton();
        tf2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        btnadd2 = new javax.swing.JButton();
        dateHD = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtTenKH = new javax.swing.JTextField();

        lbl1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl1.setText(" LẬP HÓA ĐƠN");

        lblmaphieu.setBackground(new java.awt.Color(255, 255, 255));
        lblmaphieu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblmaphieu.setText("MÃ HĐ:");

        lblmanhacc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblmanhacc.setText("           KHÁCH HÀNG:");

        lblngaylap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblngaylap.setText("NGÀY BÁN:");

        lblmanv.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblmanv.setText("MÃ NHÂN VIÊN:");

        lbltongtien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbltongtien.setText("           TỔNG TIỀN:");

        tbxuat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbxuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MÃ HÀNG", "TÊN HÀNG", "ĐƠN GIÁ", "SỐ LƯỢNG", "THÀNH TIỀN"
            }
        ));
        tbxuat.setGridColor(new java.awt.Color(204, 204, 204));
        tbxuat.setRowHeight(30);
        tbxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxuatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbxuat);

        btnadd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnadd.setText("LƯU");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsearch.setText("TÌM");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("          MÃ HĐ: ");

        lblMAHD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMAHD.setText("...");

        cbMaHD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbMaHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Chọn Mã HĐ]" }));
        cbMaHD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMaHDItemStateChanged(evt);
            }
        });

        lblManv.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblManv.setText("....");

        btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1.setText("+");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        lTien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lTien.setText("0");

        btnReport.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReport.setText("IN HÓA ĐƠN");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CHỌN HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        btn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn.setText("THÊM");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        tf2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf2FocusLost(evt);
            }
        });
        tf2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("    SỐ LƯỢNG:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("     MÃ HÀNG:");

        tf1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf1FocusLost(evt);
            }
        });
        tf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf1MouseClicked(evt);
            }
        });

        btnadd2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadd2.setText("+");
        btnadd2.setPreferredSize(new java.awt.Dimension(51, 30));
        btnadd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnadd2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        dateHD.setDateFormatString("yyyy - MM - dd");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("SĐT:");

        txtSdt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("TÌM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtTenKH.setEditable(false);
        txtTenKH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(lblngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dateHD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblmanv))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(lblMAHD, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmanhacc, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSdt)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(901, 901, 901))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(499, 499, 499)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(353, 353, 353)
                                        .addComponent(lbltongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lTien, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(515, 515, 515)
                                        .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(lblManv, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn1))
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMAHD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblmanhacc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblngaylap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dateHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        KhachHangDTO khDTO=new KhachHangDTO();
        HDonDTO hdDTO=new HDonDTO();
        //lấy giá trị mã nhà cung cấp từ combo box 1
        //String value1=(String) cb1.getSelectedItem();
        //String maNcc="";
        if(txtTenKH.equals("")) JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin Khách hàng","Thông báo",0);
        else{
            /*for(int i=0;i<value1.length();i++){
                if(value1.charAt(i)!='-') maNcc+=value1.charAt(i);
                else break;
            }*/
            khDTO.setTEN_KH(txtTenKH.getText());
            KhachHangBLL khBLL = new KhachHangBLL();
            String maKH = khBLL.getMaKH(khDTO);
            hdDTO.setMA_KH(maKH);
            hdDTO.setNGAY_LAP(new Date(dateHD.getDate().getTime()));
            hdDTO.setMA_NV(lblManv.getText());           
             //set mã HĐ cho chi tiết hóa đơn và hóa đơn
            HDonBLL hdBLL=new HDonBLL();
            ChiTietHD_DTO cthdDTO=new ChiTietHD_DTO();
            ChiTietHD_BLL cthdBLL=new ChiTietHD_BLL();
            cthdDTO.setMA_HD(lblMAHD.getText());
            hdDTO.setMA_HD(lblMAHD.getText());
            if (tbxuat.getModel().getValueAt(0, 0) != null && tbxuat.getModel().getValueAt(0, 1) != null) {
                //insert hóa đơn
                if (hdBLL.insertHDon(hdDTO) != 0) {
                    JOptionPane.showMessageDialog(null, "Tạo hóa đơn thành công!", "Thông báo", 1);
                    for (int i = 0; i < tbxuat.getModel().getRowCount(); i++) {
                        //chép dữ liệu từ table vào csdl (insert cthd)
                        cthdDTO.setMA_HANG(tbxuat.getModel().getValueAt(i, 1).toString());
                        cthdDTO.setSO_LUONG(Integer.parseInt(tbxuat.getModel().getValueAt(i, 4).toString()));
                        if (cthdBLL.insertCtietHD(cthdDTO) == 0) {
                            JOptionPane.showMessageDialog(null, "Tạo hóa đơn thất bại!", "Thông báo", 0);
                            break;
                        }
                        HangHoaDTO hangDTO = new HangHoaDTO();
                        hangDTO.setMA_HANG(tbxuat.getModel().getValueAt(i, 1).toString());
                        HangHoaBLL hangBLL = new HangHoaBLL();
                        int num = Integer.parseInt(tbxuat.getModel().getValueAt(i, 4).toString());
                        if (hangBLL.updateSL(hangDTO, -num) == 0) {
                            JOptionPane.showMessageDialog(null, "Cập nhật số lượng hàng còn lại thất bại!", "Thông báo", 0);
                        }
                    }
                    hdDTO.setTONG_TIEN(hdBLL.TongTien(hdDTO));
                    hdBLL.updateTTien(hdDTO);
                    addComboBoxMaHD();
                } else {
                    JOptionPane.showMessageDialog(null, "Tạo hóa đơn thất bại!", "Thông báo", 0);
                }
            }
            else JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng cần xuất!","Thông báo",0);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void tbxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxuatMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbxuatMouseClicked

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        HDonDTO hdDTO=new HDonDTO();
        ChiTietHD_DTO cthdDTO=new ChiTietHD_DTO();
        hdDTO.setMA_HD(String.valueOf(cbMaHD.getSelectedItem()));
        cthdDTO.setMA_HD(String.valueOf(cbMaHD.getSelectedItem()));
        if(cbMaHD.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn Hóa đơn cần tìm!","Thông báo",0);
        }
        else{
                     
            getHD(hdDTO);
            getCTHD(cthdDTO);  
        }
        //loadAll();
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        Frm_ThemKH add=new Frm_ThemKH();
        add.setVisible(true);
        add.HD=this;
        if(!txtSdt.getText().equals(""))
            add.tf4.setText(txtSdt.getText());
        add.loai = "LE";
        add.setTable();
        add.from = "HD";
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnadd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd2ActionPerformed
        // TODO add your handling code here:
        Frm_ThemHang addItem=new Frm_ThemHang();
        addItem.setVisible(true);
        addItem.LapHD=this;
        addItem.loaiPhieu = "HD";
        addItem.btn1.setVisible(false);
    }//GEN-LAST:event_btnadd2ActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        ChiTietHD_DTO cthdDTO=new ChiTietHD_DTO();        
        if(tf1.getText().equals("Nhập Mã hàng")||tf2.getText().equals("Nhập số lượng")) 
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã hàng và số lượng!","Thông báo",0);
        else{
            cthdDTO.setMA_HD(lblMAHD.getText());
            HangHoaDTO hangDTO=new HangHoaDTO();
            hangDTO.setMA_HANG(tf1.getText());
            ArrayList<HangHoaDTO> arr = new ArrayList<HangHoaDTO>();
            HangHoaBLL hangBLL = new HangHoaBLL();
            arr = hangBLL.searchHangMa(hangDTO);
            if(arr.size()==0) JOptionPane.showMessageDialog(null, "Mã sản phẩm này không tồn tại!","Thông báo",0);
            else{
                cthdDTO.setMA_HANG(tf1.getText());                
                String pattern="\\d{1,}";
                if(tf2.getText().matches(pattern )==false) JOptionPane.showMessageDialog(null, "Số lượng phải là số nguyên dương!","Thông báo",0);                
                else{
                    int so_luong=Integer.parseInt(tf2.getText());
                    int so_luongDB = hangBLL.searchHangMa(hangDTO).get(0).getSO_LUONG();
                    if(so_luong > so_luongDB)
                        JOptionPane.showMessageDialog(null, "Vượt quá số lượng còn lại","Thông báo",0);
                    else{
                        cthdDTO.setSO_LUONG(so_luong);
                        ChiTietHD_BLL cthdBLL=new ChiTietHD_BLL();
                        tongTien+=getCTHD2(dtm,stt);
                        stt++;
                        Locale locale = new Locale("en", "EN");
                        String pattern2 = "###,###.##";
                        DecimalFormat decimalFormat = (DecimalFormat)NumberFormat
                            .getNumberInstance(locale);
                        decimalFormat.applyPattern(pattern2); 
                        lTien.setText(decimalFormat.format(tongTien));
                        tf1.setText("");
                    }
                    
                }
                
            }
            
            tf2.setText("");
        }
    }//GEN-LAST:event_btnActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        HDonDTO hdDTO=new HDonDTO();     
        hdDTO.setMA_HD(lblMAHD.getText());
        HDonBLL hdBLL=new HDonBLL();        
        if(hdBLL.searchHDon(hdDTO).size()==0) JOptionPane.showMessageDialog(null,"Vui lòng thực hiện tạo hóa đơn trước khi in!","Thông báo",0);
        else{            
            hdBLL.XuatHD(hdDTO);
        } 
    }//GEN-LAST:event_btnReportActionPerformed

    private void cbMaHDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMaHDItemStateChanged
        // TODO add your handling code here:
        btnsearch.doClick();
    }//GEN-LAST:event_cbMaHDItemStateChanged

    private void tf1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf1MouseClicked
        // TODO add your handling code here:
        if(tf1.getText().equals("Nhập Mã hàng")){
            tf1.setText("");
            tf1.setForeground(Color.BLACK);
        }
            
    }//GEN-LAST:event_tf1MouseClicked

    private void tf2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf2MouseClicked
        // TODO add your handling code here:
        if(tf2.getText().equals("Nhập số lượng")){
            tf2.setText("");
            tf2.setForeground(Color.BLACK);
        }
            
    }//GEN-LAST:event_tf2MouseClicked

    private void tf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusLost
        // TODO add your handling code here:
        if(tf1.getText().equals("")){
            tf1.setText("Nhập Mã hàng");
            tf1.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_tf1FocusLost

    private void tf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusLost
        // TODO add your handling code here:
        if(tf2.getText().equals("")){
            tf2.setText("Nhập số lượng");
            tf2.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_tf2FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sdt = txtSdt.getText();
        String pattern = "^0\\d{9,10}$";
        if (sdt.matches(pattern) == false)
            JOptionPane.showMessageDialog(null, "SĐT phải bắt đầu bằng số 0, không được chứa các kí tự khác số và phải có từ 10 đến 11 chữ số!", "Thông báo", 0);
        else {
            KhachHangDTO khDTO = new KhachHangDTO();
            khDTO.setSDT(sdt);
            KhachHangBLL khBLL = new KhachHangBLL();
            String tenKH = khBLL.getTenKHBySDT(khDTO);
            if(tenKH == null){
                JOptionPane.showMessageDialog(null, "Chưa có thông tin khách hàng này. Vui lòng nhập thông tin.", "Thông báo", 0);
                btn1.doClick();
                
            }
                
            else 
                txtTenKH.setText(tenKH);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void getHD(HDonDTO hdDTO) {
	 	 
	 ArrayList<HDonDTO> arr = new ArrayList<HDonDTO>();
         NhanVienDTO nvDTO=new NhanVienDTO();
         NhanVienBLL nvBLL=new NhanVienBLL();
	 HDonBLL hdBLL = new HDonBLL();    
         KhachHangBLL khBLL=new KhachHangBLL();
         KhachHangDTO khDTO=new KhachHangDTO();
	 arr = hdBLL.searchHDon(hdDTO);
	 for (int i = 0; i < arr.size(); i++) {
            hdDTO = arr.get(i);		 
            lblMAHD.setText(hdDTO.getMA_HD()); 
            khDTO.setMA_KH(hdDTO.getMA_KH());
            txtTenKH.setText(khBLL.getKHByMaKH(khDTO).getTEN_KH());
            txtSdt.setText(khBLL.getKHByMaKH(khDTO).getSDT());
            dateHD.setDate(hdDTO.getNGAY_LAP());
            lblManv.setText(hdDTO.getMA_NV());            
            //lblTien.setText(String.valueOf(hdDTO.getTONG_TIEN()));
	}       
	 
    }
   //add hàng vào bảng với csdl
    public void getCTHD(ChiTietHD_DTO cthdDTO) {
	String[] header = { "STT","MÃ HÀNG","TÊN HÀNG","ĐƠN GIÁ","SỐ LƯỢNG","THÀNH TIỀN"};
	DefaultTableModel dtm = new DefaultTableModel(header, 0);	 
	ArrayList<ChiTietHD_DTO> arr = new ArrayList<ChiTietHD_DTO>();
	 ChiTietHD_BLL cthdBLL = new ChiTietHD_BLL();
	 arr = cthdBLL.searchCtietHD(cthdDTO);	
         int Total=0;
	 for (int i = 0; i < arr.size(); i++) {
		 cthdDTO = arr.get(i);		 
		 String id = cthdDTO.getMA_HANG();
                 HangHoaDTO hangDTO=new HangHoaDTO();
                 hangDTO.setMA_HANG(id);
                 HangHoaBLL hangBLL=new HangHoaBLL();
		 String name = hangBLL.getTenHang(hangDTO);
                 int price=hangBLL.getGia(hangDTO);
                 int num=cthdDTO.getSO_LUONG();
                 int ttien=price*num;
                 Total+=ttien;
		  Object[] row = { i+1,id, name,price,num,ttien};
		 dtm.addRow(row);
	 }
	       tbxuat.setModel(dtm);
        Locale locale = new Locale("en", "EN");
        String pattern2 = "###,###.##";
        DecimalFormat decimalFormat = (DecimalFormat) NumberFormat
                .getNumberInstance(locale);
        decimalFormat.applyPattern(pattern2);
        lTien.setText(decimalFormat.format(Total));
    }
    //add vào bảng ko dùng csdl
    public int getCTHD2(DefaultTableModel dtm,int i) {
	//int tongTien=0;
	String id =tf1.getText();
        HangHoaDTO hangDTO=new HangHoaDTO();
        hangDTO.setMA_HANG(id);
        HangHoaBLL hangBLL=new HangHoaBLL();
	String name = hangBLL.getTenHang(hangDTO);
        int price=hangBLL.getGia(hangDTO);
        int num=Integer.parseInt(tf2.getText());
        int ttien=price*num;                 
        i++;
	Object[] row = { i,id, name,price,num,ttien};
	dtm.addRow(row);	 
	 tbxuat.setModel(dtm);         
         return ttien;       
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd2;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox<String> cbMaHD;
    private com.toedter.calendar.JDateChooser dateHD;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTien;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblMAHD;
    public javax.swing.JLabel lblManv;
    private javax.swing.JLabel lblmanhacc;
    private javax.swing.JLabel lblmanv;
    private javax.swing.JLabel lblmaphieu;
    private javax.swing.JLabel lblngaylap;
    private javax.swing.JLabel lbltongtien;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tbxuat;
    public javax.swing.JTextField tf1;
    public javax.swing.JTextField tf2;
    public javax.swing.JTextField txtSdt;
    public javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables

    

}
